spring.datasource.url=jdbc:postgresql://localhost:5432/elovate
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
token.secret.key=${SECRET_KEY}
token.expiration=3600000
spring.banner.location=classpath:banner.txt
spring.servlet.multipart.enabled=true
dataloader.load.enable=true
dataloader.load.extended=false
spring.security.oauth2.client.registration.google.client_id=${GOOGLE_ID}
spring.security.oauth2.client.registration.google.client_secret=${GOOGLE_SECRET}
elovate.hostname=http://localhost:4200
elovate.api=http://localhost:8080
server.forward-headers-strategy=framework
resource.path=src/main/resources